// Package mlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mlapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExtractJSONBody defines parameters for Extract.
type ExtractJSONBody struct {
	Bbox struct {
		H int32 `json:"h"`
		W int32 `json:"w"`
		X int32 `json:"x"`
		Y int32 `json:"y"`
	} `json:"bbox"`

	// Image Base64 encoded original frame
	Image []byte `json:"image"`
}

// ExtractJSONRequestBody defines body for Extract for application/json ContentType.
type ExtractJSONRequestBody ExtractJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// Ready performs a GET /readyz (the `Ready` operationId) request.
	Ready(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExtractWithBody performs a POST /v1/features (the `Extract` operationId) request,
	// with any type of body and a specified content type.
	//
	// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
	// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
	// At most one inference at a time; overload returns 503.
	ExtractWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Extract performs a POST /v1/features (the `Extract` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
	// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
	// At most one inference at a time; overload returns 503.
	Extract(ctx context.Context, body ExtractJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// Ready performs a GET /readyz (the `Ready` operationId) request.
func (c *Client) Ready(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ExtractWithBody performs a POST /v1/features (the `Extract` operationId) request,
// with any type of body and a specified content type.
//
// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
// At most one inference at a time; overload returns 503.
func (c *Client) ExtractWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExtractRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Extract performs a POST /v1/features (the `Extract` operationId) request.
// Takes a body of the `application/json` content type.
//
// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
// At most one inference at a time; overload returns 503.
func (c *Client) Extract(ctx context.Context, body ExtractJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExtractRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewReadyRequest constructs an http.Request for the Ready method
func NewReadyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExtractRequest calls the generic Extract builder with application/json body
func NewExtractRequest(server string, body ExtractJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExtractRequestWithBody(server, "application/json", bodyReader)
}

// NewExtractRequestWithBody constructs an http.Request for the Extract method, with any body, and a specified content type
func NewExtractRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/features")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ReadyWithResponse performs a GET /readyz (the `Ready` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyResponse, error)

	// ExtractWithBodyWithResponse performs a POST /v1/features (the `Extract` operationId) request,
	// with any type of body and a specified content type.
	//
	// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
	// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
	// At most one inference at a time; overload returns 503.
	//
	// Returns a wrapper object for the known response body format(s).
	ExtractWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExtractResponse, error)

	// ExtractWithResponse performs a POST /v1/features (the `Extract` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
	// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
	// At most one inference at a time; overload returns 503.
	ExtractWithResponse(ctx context.Context, body ExtractJSONRequestBody, reqEditors ...RequestEditorFn) (*ExtractResponse, error)
}

type ReadyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		ModelVersion string `json:"model_version"`
	}
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ReadyResponse) GetJSON200() *struct {
	ModelVersion string `json:"model_version"`
} {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ReadyResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ReadyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ReadyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReadyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExtractResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Embedding    []float32 `json:"embedding"`
		ModelVersion string    `json:"model_version"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
	// JSON415 the response for an HTTP 415 `application/json` response
	JSON415 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ExtractResponse) GetJSON200() *struct {
	Embedding    []float32 `json:"embedding"`
	ModelVersion string    `json:"model_version"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ExtractResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r ExtractResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetJSON415 returns the response for an HTTP 415 `application/json` response
func (r ExtractResponse) GetJSON415() *Error {
	return r.JSON415
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ExtractResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ExtractResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ExtractResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ExtractResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExtractResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExtractResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ReadyWithResponse performs a GET /readyz (the `Ready` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyResponse, error) {
	rsp, err := c.Ready(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadyResponse(rsp)
}

// ExtractWithBodyWithResponse performs a POST /v1/features (the `Extract` operationId) request,
// with any type of body and a specified content type.
//
// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
// At most one inference at a time; overload returns 503.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ExtractWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExtractResponse, error) {
	rsp, err := c.ExtractWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExtractResponse(rsp)
}

// ExtractWithResponse performs a POST /v1/features (the `Extract` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Synchronous extraction; JSON body <= 15 MiB, decoded JPEG/PNG <= 10 MiB,
// <= 40 million pixels. Do not rotate by EXIF. BBox must be inside frame.
// At most one inference at a time; overload returns 503.
func (c *ClientWithResponses) ExtractWithResponse(ctx context.Context, body ExtractJSONRequestBody, reqEditors ...RequestEditorFn) (*ExtractResponse, error) {
	rsp, err := c.Extract(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExtractResponse(rsp)
}

// ParseReadyResponse parses an HTTP response from a ReadyWithResponse call
func ParseReadyResponse(rsp *http.Response) (*ReadyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			ModelVersion string `json:"model_version"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseExtractResponse parses an HTTP response from a ExtractWithResponse call
func ParseExtractResponse(rsp *http.Response) (*ExtractResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExtractResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Embedding    []float32 `json:"embedding"`
			ModelVersion string    `json:"model_version"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"pFRRb9s2EP4rB24PG0DLsh3vQcUeaiwJXLSZsQLbgGUYKPFssZN42vHkWgn83wdKaRxnwRonLzZFfnf8",
	"jt93d6sKqhvy6CWo7FYxhoZ8wP7jnJk4Lgrygl7i0jRN5Qojjvz4UyAf90JRYm3iqmFqkMUN8QVZjP/S",
	"NagyFYSd36i9VjWGYDZPne21YvyndYxWZX8MGQ74P/UXPOWfsBC1jwEWQ8GuiZRUppZ+aypnwfmmFQ2t",
	"N1vjKpNXCDVZrIAYaItckbFo4TPx38hDIufXFDkdJ1yx2xpBuKSR0GjVSUke3q6WCVwRNG1euQIaYkng",
	"N3SbUgIYb6FhbJgKDMH5DdRtEKiNFOVA4q8tcnDkE6WVOKmwJy7I3lTwK5auqBAu0EjLGO9SWt1FqEyl",
	"ySRJ4zNSg940TmVqlqTJTGnVGCn7px8zGtvdxOUGe+GiML1sS6sy9Us8VvpY72mavkLto8L6Deffo99I",
	"qbKJ/orQx8HP0flDL+agYnyMeTqLl37LuFaZ+mZ88PX4vsjx4Oh9n268nYzXwxP3/BsK8l/1P3a+KJk8",
	"tQFwJ2yKePAG3n38+Qpysh1ct2k6K36EyRw+uIUGi9G1Ft6tzi/Hq6vLAyDtAdf+y8ZZCrWrKkceGrfD",
	"KiTwE4EnASaJlss7OP99eZHAYkG7wUQ5gvPBWYQ1mxqTa/9WoKYgQD4erZHRFwhGwIC4Gt/cux0YpWUf",
	"YJ7Okmuv9CNPnA/lqUEZDLIg251kCGOti0emWj2wxtpUAfUjt+Q57U4MKePPmrg2ojLlvMymcTY47+q2",
	"fugx5wU3sam1+vyCmN3/x6RPxXQnxzxqgJ2KSSJhrconGkArV9+NzGODLkzAH84A/eA6YrdxcYr09lD6",
	"QCrvBAdOz+7K4Uo9iPV0Ux7gwi3uXzlRTnAD1jlaG1lnt8oJ1uFIgnVFJlq5Nrt7qe/lGB0q922dDxLW",
	"Zrcc0swn0x788PMObphN16NfM+0O3PULJt+F804Q3k9HPlZbuRu0sMVCiOG7uAVCFbKJY2CCo/n3Gjxu",
	"kcHADTLdQWMRZ4M8z5qZWp1NZieh56egp9MT0CfO+v3+3wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
